# Generated by Django 5.0.6 on 2024-06-15 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='title',
        ),
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='Lecture Name', max_length=255),
        ),
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(),
        ),
    ]
