# Generated by Django 5.0.6 on 2024-06-17 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_lecture_date_remove_lecture_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='lecture',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(to='backend.student'),
        ),
    ]
