# Generated by Django 5.0.6 on 2024-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_student_lecture_date_lecture_time_lecture_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course_code',
            field=models.CharField(default='Unknown Course_code', max_length=100),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course_title',
            field=models.CharField(default='Unknown Course_title', max_length=255),
        ),
        migrations.AddField(
            model_name='lecture',
            name='faculty',
            field=models.CharField(default='Unknown Faculty', max_length=255),
        ),
        migrations.AddField(
            model_name='lecture',
            name='venue',
            field=models.CharField(default='Unknown Venue', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default=' Unknownn Faculty', max_length=250),
        ),
    ]
