# Generated by Django 5.0.6 on 2024-06-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_lecture_course_lecture_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course_code',
            field=models.CharField(default='Unknown Course_code', max_length=255),
        ),
    ]
